### ISSUE TITLE
Text fields are not processed correctly.

### ISSUE THREAD

**Issue by AoAnima** [microo8/plgo#25]
Regarding your example concatll, when accessing a field with a text type, it gives an error "I / O error when sending backend", does not work with a field of type varchar,
I added in pl.go to the func scanVal  in 
case * string
switch oid {
case C.VARCHAROID:
* targ = C.GoString (C.datum_to_cstring (val))...

and it began to work correctly with a field of type varchar, but with field of type text does not work: (

**Comment by microo8** [comment]
I can look at it

**Comment by microo8** [comment]
When you do some changes to the plgo package, please create a pull request
