### ISSUE TITLE
go get -u github.com/microo8/plgo/...

### ISSUE THREAD

**Issue by remotejob** [microo8/plgo#3]
go get -u github.com/microo8/plgo/...

give me:

`microo8/plgo/pl.go:579: cannot use *_Cvar_SPI_processed (type C.uint32) as type C.uint64 in argument to newRows`

**Comment by microo8** [comment]
I can't replicate it. What version of postresql you have? `psql --version`

And is your system 32bit or 64bit? Anyway I've tried to explicitly type cast the `SPI_processed` var. Try it one more time.
