### ISSUE TITLE
psql server 11 

### ISSUE THREAD

**Issue by dualfade** [microo8/plgo#34]
Changed to plgo.go  --

/*
#cgo CFLAGS: -I"/usr/include/postgresql/11/server" -fpic
#cgo LDFLAGS: -shared
//{windowsCFLAGS}

So I could build go module on deb latest.

Just an fyi --

**Comment by microo8** [comment]
plgo command will replace the `/usr/include/postgresql/server` string,
with the output from `pg_config --includedir-server`

I don't know why this cgo CFLAGS is a problem to compile ...
