### ISSUE TITLE
CentOS 7 postgres.h error

### ISSUE THREAD

**Issue by GrandFelix** [microo8/plgo#4]
Hi,

Im getting this when trying to install it:

```
# github.com/microo8/plgo
/root/go/src/github.com/microo8/plgo/pl.go:7:22: fatal error: postgres.h: No such file or directory
 #include "postgres.h"
                      ^
compilation terminated.
```

I have installed all devel packages etc. Im on Pg9.6, CentOS 7

**Comment by microo8** [comment]
`plgo` runs `pg_config --includedir-server` to add the include path for pg header files.

What it prints if you run it in terminal?

If you just install it, don't worry if you have this error. The main thing is that you got the `plgo` command.

**Comment by GrandFelix** [comment]
I get /usr/pgsql-9.6/include/server and also there is postgres.h header file

**Comment by microo8** [comment]
And after you run `go get -u github.com/microo8/plgo/...` you have the `plgo` command, or it fails?

**Comment by microo8** [comment]
Try also to run just `go get -u github.com/microo8/plgo/plgo`

**Comment by GrandFelix** [comment]
This does not return any error but I dont have plgo command. Im new to go environment so maybe I did forget on something?

**Comment by microo8** [comment]
Check if the `plgo` binary exists in `$GOPATH/bin/`

**Comment by GrandFelix** [comment]
Yes it is, in home.../go/ because i did not have $GOPATH configured. Everything is OK now. Thank you

**Comment by microo8** [comment]
You can add to your `$PATH` the `$GOPATH/bin`, so you can run commands directly, right when you `go get` something.

**Comment by GrandFelix** [comment]
Ok, will do that. Thank you!
