### ISSUE TITLE
trigger DOCKER

### ISSUE THREAD

**Issue by remotejob** [microo8/plgo#8]
My extension work completely well on normal server under different PG version.

But I can't make it work in docker container, it's very strange. :(

goroutine 17 [running, locked to thread]:  ???!!

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7f5ed3227d5d]

goroutine 17 [running, locked to thread]:
main.crimeTrg(0x0, 0x0)
        /tmp/plgo140856321/package.go:48 +0x9d
main.CrimeTrg(0x7ffc9c66eeb0, 0xc400000008)
        /tmp/plgo140856321/methods.go:11 +0x3b
main._cgoexpwrap_b36115c3fa71_CrimeTrg(0x7ffc9c66eeb0, 0x1a1d0ac2cc66ca00)
        command-line-arguments/_obj/_cgo_gotypes.go:1374 +0x2d
`

All blocks on:

td.NewRow.Scan(&id)
td.FiredAfter() ....

**Comment by velo** [comment]
@remotejob can you share your dockerfile?

**Comment by remotejob** [comment]
Unfortunately for what unusual limitation I was need switch back  to PG internal notify().

So I don't have dockerfile, problem only was relate to triggers.
